### ISSUE TITLE
Container not running

### ISSUE THREAD

**Issue by geppo1988** [gotzl/accservermanager#15]
Hi, after creating the container I get the following error:

docker exec -i -t accservermanager python3 manage.py migrate
Error response from daemon: Container 2c2b446637aee42e278f7d69b909e3c2af124b58503f2c1ae937a2117c57ee8c is not running

Can you help me here? 

thanks

**Comment by geppo1988** [comment]
Some more:

docker logs accservermanager
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by gotzl** [comment]
Could you give me some more info:
* did you use plain docker or docker-compose? 
* did you build your own image or are you using the one from dockerhub?
* which version?

**Comment by gotzl** [comment]
Closing due to inactivity.
