### ISSUE TITLE
Different issues while setting up an environment for my own.

### ISSUE THREAD

**Issue by CptChaos** [gotzl/accservermanager#9]
The documentation isn't as accurate as it should be regarding the setup of this tool.
For some reason a variable as `MESSAGES` in the `/accservermanager/accservermanager/settings.py` file even has hardcoded values (by default `MESSAGES = json.load(open('/home/gotzl/workspace/accservermanager/accservermanager/messages.json', 'r'))` for some reason.

The server files don't have such a file, so I don't understand what's it for... ;)
Also the generation of a secret_key hasn't been automated.

I've got it running now, but would've been easier for others that it worked correctly.
Also the `ALLOWED_HOSTS` setting is a bit unclear to me. I try to set it to a wildcard, but doesn't seem to work. Even disabled debug mode, which requires a value for `ALLOWED_HOSTS`, but whatever I set it to, nothing seems to work and Django still starts a developmentserver on `127.0.0.1:8000`

**Comment by CoryManson** [comment]
Am receiving same issue with the file paths. Had to fork and revert the commit to get my docker image back online.

**Comment by gotzl** [comment]
Thanks for reporting ! I fixed the path in 6d6f4cd. However, I wasn't
carefull enough with the latest commit, I hope that there is nothing
more... Right now I'm away and I cannot work on it, so better stay on 0.3.0
(there should also be a image with this tag available from dockerhub).
I also promis to do more documention ;)


CoryManson <notifications@github.com> schrieb am Do., 20. Juni 2019, 11:10:

**Comment by StarkBotha** [comment]
Trying to get the dockerhub image to run on a windows machine, getting Exited (1), if i attach then i get the following error:  "CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False"

**Comment by gotzl** [comment]
Hi, try adding the ALLOWED_HOSTS as environment variable, s.t. like this to allow connections from anywhere: -e ALLOWED_HOSTS='["*"]' (not sure about all these quotes...)

**Comment by wakcs** [comment]
Hi, so i had the same issue as StarkBotha, and adding -e ALLOWED_HOSTS=['*'] to the command line got me further, but now i'm stuck on the next issue.
When starting the container, I got the following message:
`Traceback (most recent call last):
File "manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File "/home/someuser/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/home/someuser/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
settings.INSTALLED_APPS
File "/home/someuser/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
self._setup(name)
File "/home/someuser/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
self._wrapped = Settings(settings_module)
File "/home/someuser/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/accservermanager/accservermanager/settings.py", line 121, in <module>
if 'ALLOWED_HOSTS' in os.environ else []
File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)`

**Comment by gotzl** [comment]
I think that you need to use different quotation. Try `-e ALLOWED_HOSTS='["*"]'`.

**Comment by wakcs** [comment]
Tried various quotations `("['*']", ['*'], [*], ["*"], '["*"]')` neither seem to work, I have very little experience with docker, so excuse me if i'm missing something, my exact arguments in PowerShell are:
`docker run -d --name accservermanager -e SECRET_KEY=RANDOM_SEQUENCE -e ALLOWED_HOSTS=[*] -v accservermanager-data:/data -v FOLDER_ON_MY_DRIVE/server:/server -p 8000:8000 -p 9231:9231/udp -p 9232:9232/tcp gotzl/accservermanager`

**Comment by gotzl** [comment]
Ah, so you're on windows... I don't have a windows machine, so I cannot try this out, and I have no idea how the PowerShell works in trems of quotations....
May be you can try to use docker-compose ? There, this 'ugly' setting is set in the docker-compose.yaml and should not make a problem....

**Comment by gotzl** [comment]
Closing due to inactivity.
